### PR TITLE
Multiple Features - Implements old requests/issues

### PR DESCRIPTION
**Pull request by Willena**
In this pull request you will find a set of new features.

From old issues:
- Ability to ignore layer starting with an "exclude string" (implemented by @jgod, improved by me; Related subbranch : https://github.com/Willena/Photoshop-Export-Layers-to-Files-Fast/tree/jgod-ignore-layers-starting-with-bang)

- Similar to the background feature, it is now possible to keep the highest layer on top of all other layer when exporting. (Related issues : #108, #96, #42; Related subbranch : https://github.com/Willena/Photoshop-Export-Layers-to-Files-Fast/tree/first-layer-as-foreground)

- Groups can now be exported as a single image/layer. (implemented by @finscn, updated to be mergeable by me) ( related issues : #79 #70 #69 #21 #108 ; Related subbranch : https://github.com/Willena/Photoshop-Export-Layers-to-Files-Fast/tree/finscn-groups-to-layers)

- Add Transparent padding pixels before export (Related issue : #64 ; Related subbranch : https://github.com/Willena/Photoshop-Export-Layers-to-Files-Fast/tree/transparent-padding-pixels)

New Features :

- Scale image before export (Related subbranch : https://github.com/Willena/Photoshop-Export-Layers-to-Files-Fast/tree/scale-before-export)

Here is a screenshot of the UI with new parameters:
image

Feel free to comment and test my work.

### CODE REVIEW

**Comment by finscn** [comment]
WOW , great job.

But I found there are some mistakes of my fork in new PS CC.
So I updated some codes, please look this: 

https://github.com/finscn/Photoshop-Export-Layers-to-Files-Fast/commit/46fb6aa4da6c474c96b17bd009577641cbe7579a

**Comment by Willena** [comment]
I started by merging your code (using your master branch).
So, your latest fixes should be there.
Maybe you can check that everything you added is still working ? (I already did a quick test before pushing and it was working)

**Comment by jwa107** [comment]
@Willena This all sounds very great! I'm very glad you were able to address a lot of these issues. I wish I had had more time to do some of this myself as well.

I will try to test these features, and make sure performance for the base-case is still as fast as it was before and if everything looks good I will merge it into master. :)

**Comment by jwa107** [comment]
@Willena The new features see to work really great for the most part.

I did find one issue, in Photoshop CC 2018 when I use "Top groups as layers" I get the error `The command "Merge Layers" is currently unavailable`

Further, even with default settings (not using any new features) when I run this script compared to the current live version, the script take on average 1.6 seconds longer on export (with my test file). So I'm wondering if it runs a lot of extra logic now that it might not need to?

Other than that though this works wonderfully. 

If you could review the error, and see if there's anything to be done about the performance slow down that'd be great. Thanks!

**Comment by finscn** [comment]
@jwa107  , the feature "Top groups as layers" is created by me.  I'll try to fix this bug.
But , I can't reproduce it in my Photoshop CC 2018  ver 19.1.4.
Could you give the PDS file  you used in test ?

**Comment by Willena** [comment]
@finscn I've merged your commit. 

@jwa107 Can you do some new testing with the fix ? I'll try to find what causes the script to be a little longer, and make some changes if necessary.

**Comment by jwa107** [comment]
Thanks @finscn. I will retest it soon!

**Comment by finscn** [comment]
It's still slow than old version.

**Comment by Willena** [comment]
@jwa107 Thanks for merging my PR. 
I think It may be useful to closes all issues related to this PR ( #108 #96 #42 #79 #70 #69 #21 #64 )

**Comment by gloofer** [comment]
Excellent! Just excellent! Good Job developers!

**Comment by jwa107** [comment]
@Willena All done :) Thanks again!

**Comment by Petermyname** [comment]
Thanks so much for this changes.

**Comment by Willena** [comment]
@jwa107 I think #56 can also be closed. If I understand it correctly, trimming wider than the layer can be done with the padding functionality (a padding value of 1px or 2px). Am I right ?

**Comment by jwa107** [comment]
@Willena I did miss that, thanks! And yeah, I cleaned up all the issues so they should be easier to read through.

**Comment by finscn** [comment]
@Willena  I've updated my code for cosmetic . Could you create a new PR?
I'm not good at git

**Comment by jwa107** [comment]
@finscn Have you looked through here? 
https://services.github.com/on-demand/github-cli/open-pull-request-github

**Pull request merged**
